remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme 

title: Power Outages Visualization
description: "An interactive visualization of power outages across the US."
baseurl: "" 
url: "https://keemarice.github.io/PowerOutages"
